### ISSUE TITLE
How to writing log to rsyslog?

### ISSUE THREAD

**Issue by wangfakang** [cihub/seelog#101]
hi @goodsign : I want to write some loginfo to rsyslog, I'm not sure that seelog could do it?

Thanks.

**Comment by goodsign** [comment]
Hi @wangfakang!

Currently we don't have builtin syslog receiver, but you may build your own using [this example](https://github.com/cihub/seelog/wiki/custom-receivers#scenario-31-custom-receivers-without-contextwith-fixed-context)

**Comment by wangfakang** [comment]
@goodsign  Oh, Maybe I didn't say clear my question. I want using seelog lib writing my app loginfo to rsyslog and not receiver from rsyslog.
I found a [PR](https://github.com/cihub/seelog/pull/50)  and you say ' It's will release as 2.6.'  but not found anywhere. maybe i'm wrong please give me some tips thx.

**Comment by goodsign** [comment]
We included the TLS part of that PR into 2.6, but we didn't build a builtin syslog receiver yet.

Right, so you can build a syslog receiver. [Receiver](https://github.com/cihub/seelog/wiki/Dispatchers-and-receivers) is the node that receives messages, so if you need to write your logs to syslog, you need a syslog receiver. We don't have a builtin one yet, but at the moment you can build your own using the example above.

**Comment by wangfakang** [comment]
Oh, I know. Thank you for your detailed explanation.
