### ISSUE TITLE
How to specify different format according to source file difference

### ISSUE THREAD

**Issue by carbin-gun** [cihub/seelog#106]
what I want to do is logging two things :

 - record the access log with format A.(I have an interceptor file which will do this thing.)
 - record some useful messages with another format B.

How should I do this.Multiple loggers or any better ideas?

**Comment by goodsign** [comment]
Hey carbin-gun,

Yeah, one of the most simple options would be using multiple loggers. There is 'constraints/exceptions' mechanism in seelog, but it's for making log levels different for different files, but there is no such thing for formats. So yeah, try multiple loggers, seelog was designed to have low resource usage, so you won't have any overhead for using two loggers.

Note: you don't actually have to create 2 vars, you may just use one variable for the access log logger and use package level calls for everything else.

Let me know if that makes sense for you.

**Comment by carbin-gun** [comment]
hi @goodsign. 
Yeah.that's what I'm planning to do for now .But maybe the format override should be supported ,How do you think of that?

**Comment by goodsign** [comment]
Yeah, I think that might be a good idea, I'll add it to my possible future features list. Thanks for suggestion!

**Comment by carbin-gun** [comment]
looking forward to see it soom
