### ISSUE TITLE
Add the possibility to explode zipped logs

### ISSUE THREAD

**Issue by ylegat** [cihub/seelog#110]
Hello !
Popular command line utilities like `zcat` or `zgrep` are useful tools for processing log files. For instance, `zgrep` allow to search compressed files for a regular expression.
Those tools require that the analyzed archive contains only one file. Yet, when compressing archived logs, seelog put all the log files in the same archive.
    
So, it would be nice if it was possible for archived logs to be zipped in dedicated zip files. If this path was taken, and as new compression formats might be introduced in future release of `seelog`, we would want to clearly separate the choice of the compression algorithm to the choice of the gathering mode (grouped vs exploded).

Therefore, we could use a new attribute, something like `archiveexploded` (a boolean), specifying if the logs should be exploded or grouped inside the same archive file.

I'm currently working with a colleague to implement such a feature. Do you think the project would benefit from it ?

**Comment by goodsign** [comment]
Hi ylegat!

That's definitely interesting and may be useful.

**Comment by ylegat** [comment]
Hi goodsign !
As promised, here is our pull request to add the explode mode. We are waiting for your comments !
