### ISSUE TITLE
Add gzip compression algorithm

### ISSUE THREAD

**Issue by mlallaouret** [cihub/seelog#112]
Hello !

Currently seelog only proposes to use `zip` as compression algorithm. With @ylegat, we propose to add `gzip` to offer an alternative to the end users. This work could ease the introduction of other compression formats if needed.

**Comment by goodsign** [comment]
Hi!

That's a great idea. Are you going to do a pull request in addition to [the previous one](https://github.com/cihub/seelog/pull/111) or would you like me to take a look myself later?

**Comment by mlallaouret** [comment]
We are going to do a pull request.

**Comment by goodsign** [comment]
Thanks!
