### ISSUE TITLE
Can output file be named as info.log.2016.05.30?

### ISSUE THREAD

**Issue by Fall12** [cihub/seelog#119]
Hi,
As I updated to new seelog version last Friday,I found that the output file will be named info.log,and  rename date rolling log till date changed.Can we also support the old pattern which is like info.log.2016.05.30 ?
Thank you.

**Comment by goodsign** [comment]
Hey Fall12,

We changed this logic so that time and size rolling receivers work in the same way (rename after roll) and because this behavior seems more widespread. I wasn't planning to support the old pattern, but can you tell me what is your usecase and why do you need it?

Thanks!

**Comment by Fall12** [comment]
Hi goodsign,
Well,because our log file is used for statistic analysis which is done by big data department. And they process data according to date of log file's name.They also handle data from other projects  programed in Java,and Apache log4j  can make configuration for log file's name.That is why I hope seelog can be configurable.
Thank you~

**Comment by goodsign** [comment]
I've added this feature. Check out the new rolling date receiver attribute: [fullname](https://github.com/cihub/seelog/wiki/Receiver-reference#rolling-file-writer-or-rotation-file-writer).

**Comment by Fall12** [comment]
Thank you so much!
