### ISSUE TITLE
The `datepattern` attribute seems like not working in `rollingfile` output

### ISSUE THREAD

**Issue by browny** [cihub/seelog#122]
This is fine
```
"Comment": "v2.6-3-ga113d9f",
"Rev": "a113d9f1aa38f42c23712cb7c04855e9b9f30297"
```

But, this version `datepattern` seems not works
```
Comment: v2.6-22-g752ef64,                                                                                               │            
Rev: 752ef646ce438bc649b2bb565188471879185c33
```

**Comment by goodsign** [comment]
Hey browny 

Can you please give me more details: what exactly is not working in the latest revision?

**Comment by browny** [comment]
Hi @goodsign 

The latest version can not pass below test, and the config xml as below. Looks like the log file generate by the latest version **doesn't include the date postfix**. 

```go
import (
	"flag"
	"fmt"
	"os"
	"testing"
	"time"

	"rtc-middle/config"

	"github.com/stretchr/testify/assert"
)

func Test_FileOutput(t *testing.T) {
	now := time.Now()
	path := fmt.Sprintf("/var/log/middle.log.%d.%02d.%d", now.Day(), int(now.Month()), now.Year())

	// assert log file not existed
	_, err := os.Open(path)
	assert.NotNil(t, err)

	SetupLogger(config.LoadAsset("/config/asset/seelog.xml"))
	logger.Info("Hello World")

	// assert log file created
	_, err = os.Open(path)
	assert.Nil(t, err)

	// clean up
	err = os.Remove(path)
	assert.Nil(t, err)
}
```

```xml
<seelog type="sync" minlevel="debug" maxlevel="error">
	<outputs formatid="main">
		<console/>

		<rollingfile
			formatid="main"
			type="date"
			filename="/var/log/middle.log"
			datepattern="02.01.2006"
			maxrolls="5"
		/>
	</outputs>
	<formats>
		<format
			id="main"
			format="%Date(2006-01-02 15:04:05.000) [%Level] %Msg (%File, %FuncShort)%n"
		/>
	</formats>
</seelog>
```

**Comment by goodsign** [comment]
Have you seen the new changes to the rolling receiver? Now it doesn't include the prefix/postfix in the current file, but the roll files include it. If you want to also include it in the original file, you should use the `fullname` parameter. This is described in the updated [rolling receiver reference](https://github.com/cihub/seelog/wiki/Receiver-reference#rolling-file-writer-or-rotation-file-writer)

**Comment by browny** [comment]
Thanks for the reminding. After I specify the `fullname="true"`, it works as I expect.

**Comment by goodsign** [comment]
Ok, great!
