### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by UncleBig** [cihub/seelog#124]
when I write the log frequently , the program will crash whit the info like this : 
  
 fatal error: concurrent map read and map write

goroutine 23 [running]:
runtime.throw(0xca9160, 0x21)
        /work/go/src/runtime/panic.go:547 +0x90 fp=0xc82041c728 sp=0xc82041c710
runtime.mapaccess2(0x9f5ee0, 0xc820217200, 0xc8204a30f0, 0x2, 0x9f7660)
        /work/go/src/runtime/hashmap.go:343 +0x5a fp=0xc82041c770 sp=0xc82041c728
reflect.mapaccess(0x9f5ee0, 0xc820217200, 0xc8204a30f0, 0xc820217200)
        /work/go/src/runtime/hashmap.go:993 +0x35 fp=0xc82041c7a0 sp=0xc82041c770
reflect.Value.MapIndex(0x9f5ee0, 0xc820026210, 0x195, 0x9f7660, 0xc8204a30f0, 0x98, 0x0, 0x0, 0x0)
        /work/go/src/reflect/value.go:1041 +0x14a fp=0xc82041c828 sp=0xc82041c7a0
fmt.(*pp).printReflectValue(0xc8204a40d0, 0x9f5ee0, 0xc820026210, 0x195, 0xc800000076, 0x1, 0x9efe00)
        /work/go/src/fmt/print.go:904 +0x2887 fp=0xc82041cfe0 sp=0xc82041c828
fmt.(*pp).printValue(0xc8204a40d0, 0x9f5ee0, 0xc820026210, 0x195, 0xc800000076, 0x1, 0x9efe00)
        /work/go/src/fmt/print.go:848 +0x440 fp=0xc82041d0d0 sp=0xc82041cfe0
fmt.(*pp).printReflectValue(0xc8204a40d0, 0x9cce00, 0xc820026210, 0x16, 0x76, 0x0, 0x0)
        /work/go/src/fmt/print.go:1013 +0x337a fp=0xc82041d888 sp=0xc82041d0d0
fmt.(*pp).printArg(0xc8204a40d0, 0x9cce00, 0xc820026210, 0x76, 0x0, 0x0)
        /work/go/src/fmt/print.go:810 +0x540 fp=0xc82041da10 sp=0xc82041d888
fmt.(*pp).doPrintf(0xc8204a40d0, 0xc059f0, 0xf, 0xc820450700, 0x1, 0x1)
        /work/go/src/fmt/print.go:1238 +0x1dcd fp=0xc82041dd98 sp=0xc82041da10
fmt.Sprintf(0xc059f0, 0xf, 0xc820450700, 0x1, 0x1, 0x0, 0x0)
        /work/go/src/fmt/print.go:203 +0x6f fp=0xc82041dde8 sp=0xc82041dd98
github.com/cihub/seelog.(*logFormattedMessage).String(0xc820217230, 0x0, 0x0)
        /work/go_common/src/github.com/cihub/seelog/logger.go:369 +0x58 fp=0xc82041de28 sp=0xc82041dde8
github.com/cihub/seelog.(*commonLogger).processLogMsg(0xc8200e47e0, 0xb35002, 0x7f51b82b5060, 0xc820217230, 0x7f51b82b5088, 0xc8203f98f0)
        /work/go_common/src/github.com/cihub/seelog/logger.go:312 +0x8e fp=0xc82041de88 sp=0xc82041de28
github.com/cihub/seelog.(*asyncLogger).processQueueElement(0xc8200e47e0)
        /work/go_common/src/github.com/cihub/seelog/behavior_asynclogger.go:115 +0x156 fp=0xc82041df40 sp=0xc82041de88
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc8200e47e0, 0x0)
        /work/go_common/src/github.com/cihub/seelog/behavior_asynclooplogger.go:57 +0x140 fp=0xc82041df70 sp=0xc82041df40
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc8200e47e0)
        /work/go_common/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x40 fp=0xc82041df88 sp=0xc82041df70
runtime.goexit()
        /work/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82041df90 sp=0xc82041df88
created by github.com/cihub/seelog.NewAsyncLoopLogger
        /work/go_common/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x91

I'm not sure what's the reason.

**Comment by goodsign** [comment]
Hello @UncleBig 

Could you please provide a small program that reproduces this issue?

**Comment by UncleBig** [comment]
@goodsign hello .I have changed the maxsize of the logfile in the config file , it works normally 。Maybe I set the value too large before，Thank you ！
