### ISSUE TITLE
Documentation: Incorrect Syslog severity code in Custom Formatter wiki page

### ISSUE THREAD

**Issue by agy** [cihub/seelog#132]
I'd have created a PR, but I'm not sure how (or if) I can do that with the GitHub wiki for this project.

The [Syslog RFC5424](https://tools.ietf.org/html/rfc5424#section-6.2.1) linked in the code has the Syslog `warning` severity code as `4` but the wiki documents it as `5`. I believe this to be a typo.

**Table copied from RFC5424**
```
           Numerical         Severity
             Code

              0       Emergency: system is unusable
              1       Alert: action must be taken immediately
              2       Critical: critical conditions
              3       Error: error conditions
              4       Warning: warning conditions
              5       Notice: normal but significant condition
              6       Informational: informational messages
              7       Debug: debug-level messages

              Table 2. Syslog Message Severities
```

**Comment by pkorotkov** [comment]
@agy Do you mean [this](https://github.com/cihub/seelog/wiki/Custom-formatters#formatter-for-tls-connection-writing-to-syslog) mapping?

**Comment by agy** [comment]
@pkorotkov Yes. Sorry I should have provided the context.

```
--- a/Custom-formatters.md
+++ b/Custom-formatters.md
@@ -78,7 +78,7 @@ var levelToSyslogSeverity = map[log.LogLevel]int{
        log.TraceLvl:    7,
        log.DebugLvl:    7,
        log.InfoLvl:     6,
-       log.WarnLvl:     5,
+       log.WarnLvl:     4,
        log.ErrorLvl:    3,
        log.CriticalLvl: 2,
        log.Off:         7,
```

**Comment by pkorotkov** [comment]
@ary Looks sensible, thanks for your contribution!
Done.

**Comment by ary** [comment]
Hi, I think you mean @agy :)

**Comment by pkorotkov** [comment]
@ary Sure, sorry for the noise! :)

**Comment by pkorotkov** [comment]
@agy Does it work for you?

**Comment by agy** [comment]
@pkorotkov It better, it's in production ;-)

In all seriousness, I've successfully tested the change using the setups below.

### Ubuntu 14.04
```
agy@trusty:~$ dpkg-query --show rsyslog
rsyslog	7.4.4-1ubuntu2.6
```

```
agy@trusty:~$ grep -i udp /etc/rsyslog.conf
# provides UDP syslog reception
$ModLoad imudp
$UDPServerRun 514
```

```
agy@trusty:~$ grep warn.log /etc/rsyslog.d/50-default.conf
*.=warn				-/var/log/warn.log
```

### Ubuntu 16.04

```
agy@xenial:~$ dpkg-query --show rsyslog
rsyslog	8.16.0-1ubuntu3
```

```
agy@xenial:~$ grep -i udp /etc/rsyslog.conf
# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")
```

```
agy@xenial:~$ grep warn.log /etc/rsyslog.d/50-default.conf
*.=warn				-/var/log/warn.log
```

I cannot vouch for other distributions for syslog servers, however I feel pretty safe that this is correct with this configuration.

Using the documented severity level (of `5`) does not make warning log messages appear in the `warn.log` file as expected.
