### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by fwhappy** [cihub/seelog#134]
fatal error: concurrent map read and map write

goroutine 8 [running]:
runtime.throw(0x48b6d6, 0x21)
    /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42050b8f0 sp=0xc42050b8d0
runtime.mapaccess2(0x41f6e0, 0xc4204aee40, 0xc42042c388, 0xc42042c3c8, 0xc4200d92f8)
    /usr/local/go/src/runtime/hashmap.go:340 +0x249 fp=0xc42050b938 sp=0xc42050b8f0
reflect.mapaccess(0x41f6e0, 0xc4204aee40, 0xc42042c388, 0xc4204aee40)
    /usr/local/go/src/runtime/hashmap.go:1008 +0x3f fp=0xc42050b970 sp=0xc42050b938
reflect.Value.MapIndex(0x41f6e0, 0xc4204aee40, 0x15, 0x3ebd20, 0xc42042c388, 0x82, 0x3ebd20, 0xc42042c3c8, 0x82)
    /usr/local/go/src/reflect/value.go:1040 +0x128 fp=0xc42050b9f8 sp=0xc42050b970
fmt.(*pp).printValue(0xc420350e40, 0x41f6e0, 0xc4204aee40, 0x15, 0x76, 0x0)
    /usr/local/go/src/fmt/print.go:738 +0x120f fp=0xc42050bbe8 sp=0xc42050b9f8
fmt.(*pp).printArg(0xc420350e40, 0x41f6e0, 0xc4204aee40, 0x76)
    /usr/local/go/src/fmt/print.go:668 +0x1f5 fp=0xc42050bce0 sp=0xc42050bbe8
fmt.(*pp).doPrintf(0xc420350e40, 0x487b3b, 0x19, 0xc42042c370, 0x1, 0x1)
    /usr/local/go/src/fmt/print.go:985 +0x123d fp=0xc42050bdc8 sp=0xc42050bce0
fmt.Sprintf(0x487b3b, 0x19, 0xc42042c370, 0x1, 0x1, 0xc42050be68, 0x0)
    /usr/local/go/src/fmt/print.go:196 +0x6a fp=0xc42050be20 sp=0xc42050bdc8
github.com/cihub/seelog.(*logFormattedMessage).String(0xc4204f2330, 0x4bc001, 0x661200)
    /Users/xh/gojob/src/github.com/cihub/seelog/logger.go:369 +0x52 fp=0xc42050be68 sp=0xc42050be20
github.com/cihub/seelog.(*commonLogger).processLogMsg(0xc42008e900, 0x436401, 0x65a1e0, 0xc4204f2330, 0x661200, 0xc42031a310)
    /Users/xh/gojob/src/github.com/cihub/seelog/logger.go:312 +0x9c fp=0xc42050beb0 sp=0xc42050be68
github.com/cihub/seelog.(*asyncLogger).processQueueElement(0xc42008e900)
    /Users/xh/gojob/src/github.com/cihub/seelog/behavior_asynclogger.go:115 +0x118 fp=0xc42050bf50 sp=0xc42050beb0
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc42008e900, 0x0)
    /Users/xh/gojob/src/github.com/cihub/seelog/behavior_asynclooplogger.go:57 +0xef fp=0xc42050bf78 sp=0xc42050bf50
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc42008e900)
    /Users/xh/gojob/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x44 fp=0xc42050bf98 sp=0xc42050bf78
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42050bfa0 sp=0xc42050bf98
created by github.com/cihub/seelog.NewAsyncLoopLogger
    /Users/xh/gojob/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x9f

**Comment by pkorotkov** [comment]
@fwhappy thanks for your bug report!
Could you please provide a code snippet to reproduce this error?

**Comment by axengine** [comment]
I got the same fatal error,release V2.6.
fatal error: concurrent map read and map write

goroutine 8 [running]:
runtime.throw(0x9b86a0, 0x21)
	c:/go/src/runtime/panic.go:530 +0x90 fp=0xc82038d268 sp=0xc82038d250
runtime.mapaccess2(0x90c020, 0xc8202dc8d0, 0xc820205560, 0xc, 0x7dca20)
	c:/go/src/runtime/hashmap.go:343 +0x5a fp=0xc82038d2b0 sp=0xc82038d268
reflect.mapaccess(0x90c020, 0xc8202dc8d0, 0xc820205560, 0xc8202dc8d0)
	c:/go/src/runtime/hashmap.go:993 +0x35 fp=0xc82038d2e0 sp=0xc82038d2b0
reflect.Value.MapIndex(0x90c020, 0xc8202dc8d0, 0x15, 0x7dca20, 0xc820205560, 0x98, 0x0, 0x0, 0x0)
	c:/go/src/reflect/value.go:1041 +0x14a fp=0xc82038d368 sp=0xc82038d2e0
fmt.(*pp).printReflectValue(0xc8204c04e0, 0x90c020, 0xc8202dc8d0, 0x15, 0x76, 0x0, 0xc81ffd9f00)
	c:/go/src/fmt/print.go:904 +0x2887 fp=0xc82038db20 sp=0xc82038d368
fmt.(*pp).printArg(0xc8204c04e0, 0x90c020, 0xc8202dc8d0, 0x76, 0x0, 0x0)
	c:/go/src/fmt/print.go:810 +0x540 fp=0xc82038dca8 sp=0xc82038db20
fmt.(*pp).doPrint(0xc8204c04e0, 0xc8202d2c80, 0xa, 0xa, 0x430000)
	c:/go/src/fmt/print.go:1273 +0x24d fp=0xc82038dda8 sp=0xc82038dca8
fmt.Sprint(0xc8202d2c80, 0xa, 0xa, 0x0, 0x0)
	c:/go/src/fmt/print.go:239 +0x62 fp=0xc82038ddf8 sp=0xc82038dda8
github.com/cihub/seelog.(*logMessage).String(0xc820276b80, 0x0, 0x0)
	D:/go/src/github.com/cihub/seelog/logger.go:365 +0x42 fp=0xc82038de28 sp=0xc82038ddf8
github.com/cihub/seelog.(*commonLogger).processLogMsg(0xc82009a510, 0x8bcb01, 0x7f1703156c80, 0xc820276b80, 0x7f1703156ca8, 0xc82038e4d0)
	D:/go/src/github.com/cihub/seelog/logger.go:312 +0x8e fp=0xc82038de88 sp=0xc82038de28
github.com/cihub/seelog.(*asyncLogger).processQueueElement(0xc82009a510)
	D:/go/src/github.com/cihub/seelog/behavior_asynclogger.go:115 +0x156 fp=0xc82038df40 sp=0xc82038de88
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc82009a510, 0x0)
	D:/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:57 +0x140 fp=0xc82038df70 sp=0xc82038df40
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc82009a510)
	D:/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x40 fp=0xc82038df88 sp=0xc82038df70
runtime.goexit()
	c:/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82038df90 sp=0xc82038df88
created by github.com/cihub/seelog.NewAsyncLoopLogger
	D:/go/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x91

**Comment by axengine** [comment]
seelog是异步写日志，如果带写的日志是一个map，而这个map在其他协程中有写入，就有可能会出现这个问题。

**Comment by fwhappy** [comment]
@axengine 

非常感谢

之前一直以为是seelog内部的问题，看来是我的用法有问题


之前不知道怎么解决这个，已经将日志库从seelog换成了beelog，汗

**Comment by lwithers** [comment]
Same as #136 I think.
