### ISSUE TITLE
runtime panic,i don`t kwon why

### ISSUE THREAD

**Issue by 756445638** [cihub/seelog#136]
fatal error: concurrent map read and map write

goroutine 23 [running]:
runtime.throw(0x971b9a, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42021d508 sp=0xc42021d4e8
runtime.mapaccess2(0x8d9c20, 0xc420196db0, 0xc4203f1130, 0xc420222230, 0xc4203f1101)
	/usr/local/go/src/runtime/hashmap.go:340 +0x249 fp=0xc42021d550 sp=0xc42021d508
reflect.mapaccess(0x8d9c20, 0xc420196db0, 0xc4203f1130, 0xc420196db0)
	/usr/local/go/src/runtime/hashmap.go:1008 +0x3f fp=0xc42021d588 sp=0xc42021d550
reflect.Value.MapIndex(0x8d9c20, 0xc42000c840, 0x1b5, 0x8b6180, 0xc4203f1130, 0xb8, 0x8d2560, 0xc42001c120, 0x36)
	/usr/local/go/src/reflect/value.go:1040 +0x128 fp=0xc42021d610 sp=0xc42021d588
fmt.(*pp).printValue(0xc4204bb800, 0x8d9c20, 0xc42000c840, 0x1b5, 0x76, 0x2)
	/usr/local/go/src/fmt/print.go:738 +0x120f fp=0xc42021d800 sp=0xc42021d610
fmt.(*pp).printValue(0xc4204bb800, 0x91e080, 0xc42000c840, 0x199, 0xc400000076, 0x1)
	/usr/local/go/src/fmt/print.go:764 +0x239b fp=0xc42021d9f0 sp=0xc42021d800
fmt.(*pp).printValue(0xc4204bb800, 0x8d2620, 0xc42000c840, 0x16, 0x76, 0x0)
	/usr/local/go/src/fmt/print.go:835 +0x1b1d fp=0xc42021dbe0 sp=0xc42021d9f0
fmt.(*pp).printArg(0xc4204bb800, 0x8d2620, 0xc42000c840, 0xc400000076)
	/usr/local/go/src/fmt/print.go:668 +0x1f5 fp=0xc42021dcd8 sp=0xc42021dbe0
fmt.(*pp).doPrintf(0xc4204bb800, 0x965968, 0xb, 0xc4203f0da0, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:985 +0x123d fp=0xc42021ddc0 sp=0xc42021dcd8
fmt.Sprintf(0x965968, 0xb, 0xc4203f0da0, 0x1, 0x1, 0xc42021de60, 0x0)
	/usr/local/go/src/fmt/print.go:196 +0x6a fp=0xc42021de18 sp=0xc42021ddc0
github.com/cihub/seelog.(*logFormattedMessage).String(0xc420196c30, 0xa04700, 0xc001a0)
	/home/yuyang/doc/yuy/gopath/src/github.com/cihub/seelog/logger.go:369 +0x52 fp=0xc42021de60 sp=0xc42021de18
github.com/cihub/seelog.(*commonLogger).processLogMsg(0xc4200ba900, 0x90a900, 0xbf6440, 0xc420196c30, 0xc001a0, 0xc42010b1f0)
	/home/yuyang/doc/yuy/gopath/src/github.com/cihub/seelog/logger.go:312 +0x9c fp=0xc42021dea8 sp=0xc42021de60
github.com/cihub/seelog.(*asyncLogger).processQueueElement(0xc4200ba900)
	/home/yuyang/doc/yuy/gopath/src/github.com/cihub/seelog/behavior_asynclogger.go:115 +0x118 fp=0xc42021df48 sp=0xc42021dea8
github.com/cihub/seelog.(*asyncTimerLogger).processItem(0xc4200ba900, 0xc4204ade00)
	/home/yuyang/doc/yuy/gopath/src/github.com/cihub/seelog/behavior_asynctimerlogger.go:68 +0xef fp=0xc42021df70 sp=0xc42021df48
github.com/cihub/seelog.(*asyncTimerLogger).processQueue(0xc4200ba900)
	/home/yuyang/doc/yuy/gopath/src/github.com/cihub/seelog/behavior_asynctimerlogger.go:74 +0x48 fp=0xc42021df98 sp=0xc42021df70
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42021dfa0 sp=0xc42021df98
created by github.com/cihub/seelog.NewAsyncTimerLogger
	/home/yuyang/doc/yuy/gopath/src/github.com/cihub/seelog/behavior_asynctimerlogger.go:51 +0x12b

**Comment by pkorotkov** [comment]
@756445638 thanks for your bug report!
Could you please provide a code snippet to reproduce this error?

**Comment by hellozenghui** [comment]
I have also encountered this problem
It does not occur after delete the log
code:
log.Errorf("out of delayMax stat:%v", stat)
stat is a map,size around 8000 byte

**Comment by 756445638** [comment]
ok,i will try!!

**Comment by lwithers** [comment]
I think this occurs because the map (`stat` in the example of @hellozenghui ) is being accessed asynchronously by seelog, meaning it can be read by seelog after the call to e.g. `log.Errorf()` returns. Since there's no lock protecting against concurrent access, if the application modifies the map, this panic will occur.

You could switch to a [synchronous](https://github.com/cihub/seelog/wiki/Logger-types#synchronous) logger to avoid this, or simply format the map value before passing the result to seelog, i.e.:

```go
statfmt := fmt.Printf("%v", stat)
log.Errorf("out of delayMax stat:%s", statfmt)
```

This also gives you the opportunity to write a nicer formatter for the map if you need it (e.g. sorting the output to occur in lexical order or something).

**Comment by fwhappy** [comment]
seelog是异步写日志，如果带写的日志是一个map，而这个map在其他协程中有写入，就有可能会出现这个问题。

**Comment by 756445638** [comment]
恩，知道了，使用上的问题

**Comment by 756445638** [comment]
yes,I have aware of that,I have removed  logging with map,problem solved ,thanks!!
