### ISSUE TITLE
Log files get rotated for each log message

### ISSUE THREAD

**Issue by vigneshr6** [cihub/seelog#145]
I can't find any mistake in this code.But log file gets rotated for each log message.
Can you solve this?

`package main

import (
	log "github.com/cihub/seelog"
)

func main() {
	testConfig := `
<seelog>
	<outputs>    <filter levels="trace">
                <rollingfile formatid="main" type="size" filename="./logs/roll.log" maxsize="100" maxrolls="5" />
    </filter>
    <filter levels="info">
         <console/>
    </filter>
	</outputs>
	    <formats>
        <format id="main" format="%Date/%Time [%LEVEL] %Msg%n"/>
		</formats>
</seelog>`

	logger, _ := log.LoggerFromConfigAsBytes([]byte(testConfig))
	log.ReplaceLogger(logger)
	log.Info("Hi")
	for i := 0; i < 200000; i++ {
		log.Trace("The time is now:>>>>>>>")
	}
}
`

**Comment by lwithers** [comment]
The unit for `maxsize` is bytes — so this configuration is telling `seelog` to rotate every 100 bytes. This explains what you are seeing.

The docs for this are at https://github.com/cihub/seelog/wiki/Receiver-reference#rolling-file-writer-or-rotation-file-writer and you can see that `maxsize` configured in bytes there.
