### ISSUE TITLE
Not all messages are written to log with multiple processes logging to same file

### ISSUE THREAD

**Issue by mratzloff** [cihub/seelog#44]
I have a program that logs in high volume to a single log file.  If I start more than one of these, only some messages reach the log.  For example, with two processes, approximately 1/2 the messages reach the log.  With three, 2/3.  With four, 3/4.

Note that these are multiple processes, not a single process using channels.  It happens even if I flush after each message.

I suspect this is some kind of lock contention problem in the library.  I am using the default logging behavior, and the newest release via `go get github.com/cihub/seelog`.

When I swapped out seelog with simply writing bytes to os.File, it works as expected: all messages are written to the log.

**Comment by navneetk** [comment]
I am facing this issue now. I am at version https://github.com/cihub/seelog/commit/5841159c495ad98691aac2bf90113c040e62bac2 
I have 4 different processes writing to the same log file.
