### ISSUE TITLE
writers_smtpwriter.go 中有错误！！！

### ISSUE THREAD

**Issue by guorui22** [cihub/seelog#55]
line 40 ：rfc5321SubjectPattern = "From: %s <%s>\nSubject: %s\n" 
应写为：rfc5321SubjectPattern = "From: %s <%s>\nSubject: %s\n\n"

否则接收方看到的邮件没有正文内容：），this tested on gmail、qq、139 。

**Comment by fjjiaboming** [comment]
@pkorotkov   What are you waiting for ?

**Comment by timesking** [comment]
I translate it for you.
He said you should add "\n" one more at the end of rfc5321SubjectPattern, otherwise the email receiver can't see body content. He tested it with gmail and some other Chinese email  providers like qq.com.

**Comment by goodsign** [comment]
Closed by [PR 76](https://github.com/cihub/seelog/pull/76)
