### ISSUE TITLE
Seelog panics on parsing error in config file

### ISSUE THREAD

**Issue by bong0** [cihub/seelog#74]
Seelog is not able to handle the following syntax error:

        <format id="nocolor-hrtime" format="%Date('02.01.2006/15:04:05' [%Lev] %FuncShort:%Msg%n"/>
with throwing an error.

    1424719067522657234 [Critical] PANIC: runtime error: slice bounds out of range
    1424719067522908091 [Debug] Stack of 1024 bytes: goroutine 16 [running]:
    github.com/bong0/project/module.skeleton.Panic()
    /home/user/dev/go/src/github.com/bong0/project/module/module.go:259 +0x166
    github.com/bong0/project/module1.Panic·i(0x0)
    <autogenerated>:33 +0x27
    runtime.panic(0x767240, 0xbb4a8f)
    /usr/lib/golang/src/pkg/runtime/panic.c:248 +0x18d
    github.com/cihub/seelog.(*formatter).findparameter(0xc20804cbc0, 0x5, 0x0, 0x0, 0xc2080015b0, 0x1)
    /home/bongo/dev/go/src/github.com/cihub/seelog/format.go:285 +0x13a
    github.com/cihub/seelog.(*formatter).findFormatterFuncParametrized(0xc20804cbc0, 0xc208036a48, 0x4, 0x1, 0x0, 0x0, 0x748301)
    /home/user/dev/go/src/github.com/cihub/seelog/format.go:258 +0x129
    github.com/cihub/seelog.(*formatter).extractFormatterFunc(0xc20804cbc0, 0x1, 0x0, 0xbcc5b0, 0x0, 0x0)
    /home/user/dev/go/src/github.com/cihub/seelog/format.go:209 +0x25d
    github.com/cihub/seelog.(*formatter).buildFormatterFuncs(0xc20804cbc0, 0x0, 0x0)
    /home/bongo/dev/go/src/github.com/cihub
    
    1424719067522925949 [Trace] Cleanup() called

Instead it runs into my panic handler. Maybe `log.ReplaceLogger(state.Logger)` should return an error? I'm not sure

**Comment by goodsign** [comment]
Yeah, it definitely should be an error. I'll look at it.
