### ISSUE TITLE
Creating a LoggingInterface using a writer and as well as rolling files

### ISSUE THREAD

**Issue by jonbonazza** [cihub/seelog#78]
First off, sorry if I missed this, but at the moment, we are supporting logging to console output as well as a rolling file via seelog configuration file, but what we really want to do is support rolling file as well as log to stderr.

We were able to log to stderr by creating a custom Writer implementation then creating a LoggingInterface from that, but then we loose the rolling file capabilities (and logging config in general).

Obviously, the easy solution is to use two separate LoggingInterfaces, but would be nice if we could use the same LoggingInterface for both (while we are using Stderr, we are not necessarily logging an error. The reasons for this are complicated and irrelevant for this post).

Is there a solution for this? For example, is there a way to programmatically construct a LoggingInterface implementation from config and then append a custom Writer implementation?

**Comment by goodsign** [comment]
Have you tried this [recipe](https://github.com/cihub/seelog/wiki/Custom-receivers#scenario-31-custom-receivers-without-contextwith-fixed-context)?

Here we show how to create a custom receiver and then use it inside a config with a ```<myreceiver>``` tag. You can name it ```<stderr>``` and use it in your config as well as the rolling file receiver and others.

**Comment by jonbonazza** [comment]
We have managed to fix this using your suggestion. Thanks!
