### ISSUE TITLE
gorouine leak when ReplaceLogger

### ISSUE THREAD

**Issue by timesking** [cihub/seelog#86]
Hi, 

I just found `asnLoopLogger.closed` had never been set as `true`.
When I try to ReplaceLogger in runtime with new config each time, one more gorouine stuck in func processItem at `asnLoopLogger.queueHasElements.Wait()`. That introduce a gorouine dead wait.

Could you take a look and fix it?

```
func (asnLoopLogger *asyncLoopLogger) processItem() (closed bool) {
	asnLoopLogger.queueHasElements.L.Lock()
	defer asnLoopLogger.queueHasElements.L.Unlock()

	for asnLoopLogger.msgQueue.Len() == 0 && !asnLoopLogger.closed {
		asnLoopLogger.queueHasElements.Wait()
	}

	if asnLoopLogger.closed {
		return true
	}

	asnLoopLogger.processQueueElement()
	return false
}
```

**Comment by goodsign** [comment]
Hi timesking,

Could you please attach a full working example which reproduces this issue.

Thanks!

**Comment by timesking** [comment]
I will do it later.

**Comment by goodsign** [comment]
Actually, I guess I know what the problem is. Please try the latest revision.

**Comment by timesking** [comment]
I'm sure your commit has fixed my problem. Thx.
