### ISSUE TITLE
Rotation config example

### ISSUE THREAD

**Issue by mtyurt** [cihub/seelog#89]
Is there any configuration example for logging with time interval rotation? For example daily? I wandered around the source code but it's not easy :)  Can you provide/refer to a sample doc page or blogpost?

**Comment by goodsign** [comment]
Hi mtyurt!

Have you checked the [wiki page](https://github.com/cihub/seelog/wiki/Receiver-reference#rolling-file-writer-or-rotation-file-writer) for the rotation writer itself?

This part is relevant:


> Attributes, allowed with 'date' type:
>
> * datepattern - This is the pattern that would be used in 'time.LocalTime().Format' to form a file name. The "date" (actually, this means both date & time) rolling occurs when 'time.LocalTime().Format(rollFileWriter.datePattern)' returns something different than the current file name. This means that you create daily rotation using a format with a day identifier like "02.01.2006". Or you can create an hourly rotation using a format with an hour identifier like "02.01.2006.15".


So, basically, it uses a super simple idea: you create pattern and it checks, whether current time representation (using the pattern) changed or not. If yes, then it rotates.

**Comment by mtyurt** [comment]
Oh, figured out know. Thank you :)
