### ISSUE TITLE
using env variables in xml file

### ISSUE THREAD

**Issue by tubaozturk** [cihub/seelog#90]
Hi, 
Is it possible to define filename path dynamically, with an environment variable etc.
What I want to do is something like this:
```xml
<rollingfile type="date" filename="os.GetEnv(logpath)/roll.log" datepattern="02.01.2006"/>
```

**Comment by goodsign** [comment]
Hi!

Currently, no, but as long as config is just a string, you can use any golang template packages to create it dynamically in runtime before loading the logger.

**Comment by tubaozturk** [comment]
Will do, thanks!
