### ISSUE TITLE
Examples for configuring with code

### ISSUE THREAD

**Issue by theduke** [cihub/seelog#95]
Neither can I nor do I want to use the xml format for logger configuration.

Sadly there are zero examples for configuring filters/receivers in code.

Could you add some?

**Comment by goodsign** [comment]
Hey theduke,

Currently there is no possibility to configure logger in code, only to generate xml in code. Basically there are no technical difficulties in providing such a feature, it just wasn't needed. You could help with a PR or I could look into it later, but there is no such feature currently.

**Comment by theduke** [comment]
Shame, I was really looking forward to using seelog but I need really need to set it up in code.
I'll probably be too busy to implement this myself though.

**Comment by goodsign** [comment]
I'm having a really busy time now, so a couple of other issues are stacked for a month already. But I could look into it in a few weeks, if that works for you.

**Comment by goodsign** [comment]
Hey theduke,

Finally I returned to my normal work schedule. I just made a simple change to the package and just made public most of the constructors. So now you can do something like this:

```go
package main

import log "github.com/cihub/seelog"

func main() {
	defer log.Flush()
	log.Info("Hello from Seelog!")

	consoleWriter, _ := log.NewConsoleWriter()
	formatter, _ := log.NewFormatter("%Level %Msg %File%n")
	root, _ := log.NewSplitDispatcher(formatter, []interface{}{consoleWriter})
	constraints, _ := log.NewMinMaxConstraints(log.TraceLvl, log.CriticalLvl)
	specificConstraints, _ := log.NewListConstraints([]log.LogLevel{log.InfoLvl, log.ErrorLvl})
	ex, _ := log.NewLogLevelException("*", "*main.go", specificConstraints)
	exceptions := []*log.LogLevelException{ex}

	logger := log.NewAsyncLoopLogger(log.NewLoggerConfig(constraints, exceptions, root))
	log.ReplaceLogger(logger)

	log.Trace("This should not be seen")
	log.Debug("This should not be seen")
	log.Info("Test")
	log.Error("Test2")
}
```

This is just a demonstration of all the features possible, so probably your case would be more simple. I've also added a part to the documentation that says that configuration in code is not a recommended way, but is now possible.

Let me know what you think.

**Comment by vrecan** [comment]
:+1:

**Comment by vrecan** [comment]
is there a way to programmatically set different formatters for different log levels?

**Comment by goodsign** [comment]
It's the same as doing it using xml config:

```xml
<outputs>
        <filter levels="critical" formatid="your_format">
   ...
```

So you need to create a filtering dispatcher and assign format id to it, because you can only assign formats to dispatchers currently.
