### ISSUE TITLE
Body in gmail is empty

### ISSUE THREAD

**Issue by mcmaur** [cihub/seelog#98]
Using the smtp function in the full format of the mail the message is present under "Subject:" but in the normal view of gmail the body is empty.

Full message:
```
Date: Mon, 26 Oct 2015 03:44:49 -0700 (PDT)
From: mchx Totem Error <noreply@--.com>
Subject: Diagnostic message from server: 
[CRITICAL] 2015-10-26 11:44:46 Problem bad connection
```
![ggmall](https://cloud.githubusercontent.com/assets/3799031/10727613/7b7863c4-7bdb-11e5-9702-bb689e616273.jpg)

**Comment by goodsign** [comment]
Hi mcmaur!

Can you post the snippet you are using to reproduce, seelog config and the revision of seelog you are using?

**Comment by mcmaur** [comment]
I can't see any problem on code and configuration because the email is sent and received correctly. I am not able to specify the version I was using because of vendoring problems.
Once updated the library to the latest version the problem is vanished.

###### Code: 
```
if err != nil {
		log.Critical("Problem ", err)
		os.Exit(1)
	}
```
###### Configuration:
```
<filter levels="error,critical">
      <file path="./log/error.log" formatid="common"/>
      <smtp formatid="common" senderaddress="noreply@---.com" sendername="mchx Totem Error" hostname="smtp.gmail.com" hostport="587" username="noreply@---.com" password="//">
         <recipient address="--@--.com"/>
      </smtp>
    </filter>
```
